### ISSUE TITLE
Typo in quest book

### ISSUE THREAD

**Issue by NotCletus** [TheOnlyRupert/GoldenTigerModpack#2]
yo homie,

you put an "s" at the of "hand" in the quest "Basics of Survival: Ataxophobia: The Cake is a Lie"

yor realiest home skillet
*insert signing thing here*
NotCletus

**Comment by TheOnlyRupert** [comment]
STOP playing the pack and throw your computer out the window. This is a serious problem that can lead to spontaneous combustion of your computer.

All joking aside, I will fix thanks TheOnlyCletus!
